### ISSUE TITLE
Binding of save/load states and slots to joystick buttons

### ISSUE THREAD

**Issue by petmac** [petmac/DOSBox#6]

**Comment by ScHlAuChii** [comment]
The standard behavior for this in most emulators is
Shift+F1 = Save State to Slot 1     F1 = Load State from Slot 1
Shift+F2 = Save State to Slot 2     F2 = Load State from Slot 2
etc...

Shift+F-Keys for savestating will be fine, as DosBox doesnt seem to use that combination.
However using the F-Keys for loading might conflict with games that use the F-Keys for ingame functions, so loading would require a different combination, I suggest ALT+F1 etc...

**Comment by ScHlAuChii** [comment]
AVI recording does not automatically restart when you load a savestate on any other state beside F1!

**Comment by petmac** [comment]
Issue has not recurred; may be specific to Mega Race.
